
all:
	$(CC) -O2 -Wall -I../include -o dspUpload dspUpload.c
	$(CC) -O2 -Wall -I../include -o setTrig setTrig.c
	$(CC) -O2 -Wall -I../include -o getStatus getStatus.c
	$(CC) -O2 -Wall -I../include -o setTime setTime.c

setTrig:
	$(CC) -O2 -Wall -I../include -o setTrig setTrig.c

setTime:
	$(CC) -O2 -Wall -I../include -o setTime setTime.c
clean:
	rm setTrig
	rm getStatus
	rm setTime
#	rm user