
OBJSX=HardwareXml.x \
HardwareXmlHandler.x \
NodeXml.x \
FieldXml.x \
NodeXmlHandler.x \
PersistParameterHandler.x \
ExtraInfoXml.x \
XmlParser.x

include ../../Makefile.inc.def

all: $(OBJS) \
	build/FSXML.a

include ../../Makefile.inc.rules
